name = "SlurmClusterManager"
uuid = "c82cd089-7bf7-41d7-976b-6b5d413cbe0a"
authors = ["Joseph Kleinhenz <kleinhenz.joseph@gmail.com>"]
version = "0.1.4"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.0"
