name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '1.6.7'
          - '1.9.3'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker
        run: |
          docker version
          docker-compose version
          docker build --build-arg JULIA_VERSION=${{matrix.version}} -t slurm-cluster-julia -f ci/Dockerfile .
          docker-compose -f ci/docker-compose.yml up -d
          docker ps
      - name: Test Docker
        run: |
          docker exec -t slurmctld julia --version
          docker exec -t slurmctld srun -n 4 hostname
      - name: Test SlurmClusterManager
        run: |
          docker exec -t slurmctld julia -e 'import Pkg; Pkg.activate("SlurmClusterManager"); Pkg.test()'
